<?php

$lang = array(
    'ru' => array(
        'title' => 'Генератор водяных знаков',
        'settings' => 'Настройки',
        'image' => 'Исходное изображение',
        'watermark' => 'Водяной знак',
        'position' => 'Положение',
        'transparency' => 'Прозрачность',
        'reset' => 'Сброс',
        'download' => 'Скачать',
        'copyright' => 'Это мой сайт, пожалуйста, не копируйте и не воруйте его.',
        'notInput' => 'Заполните ',
        'notImage' => 'Выберите ',
        'bigFile' => 'Файл больше 2МБ',
        'wrongExtension' => 'Неверное расширение',
        'wrongOrigin' => 'Неправильное смещение',
        'errorDownload' => 'Ошибка при скачивании',
        'successTransfer' => 'Файл передан',
        'origin-x' => 'Cмещение по X',
        'origin-y' => 'Cмещение по Y',
        'original-image' => 'Исходное изображение',
        'watermark-image' => 'Водяной знак',
    ),
    'en' => array(
        'title' => 'Watermarks generator',
        'settings' => 'Settings',
        'image' => 'Original image',
        'watermark' => 'Watermark',
        'position' => 'Position',
        'transparency' => 'Opacity',
        'reset' => 'Reset',
        'download' => 'Download',
        'copyright' => 'It`s my site, please, don`t copy or steal it.',
        'notInput' => 'Fill ',
        'notImage' => 'Choose ',
        'bigFile' => 'File size > 2MB',
        'wrongExtension' => 'Wrong extension',
        'wrongOrigin' => 'Wrong offset',
        'errorDownload' => 'Download error',
        'successTransfer' => 'File transferred',
        'origin-x' => 'Offset X',
        'origin-y' => 'Offset Y',
        'original-image' => 'Original image',
        'watermark-image' => 'Watermark',
    )
);
