<?php

$lang = array(
    'ru' => array(
        'title' => 'Генератор водяных знаков',
        'settings' => 'Настройки',
        'image' => 'Исходное изображение',
        'watermark' => 'Водяной знак',
        'position' => 'Положение',
        'transparency' => 'Прозрачность',
        'reset' => 'Сброс',
        'download' => 'Скачать',
        'copyright' => 'Это мой сайт, пожалуйста, не копируйте и не воруйте его.',
        'notInput' => 'Заполните ',
        'notImage' => 'Выберите ',
        'bigFile' => 'Файл больше 2МБ',
        'wrongExtension' => 'Неверное расширение',
        'wrongOrigin' => 'Неправильное смещение',
        'errorDownload' => 'Ошибка при скачивании',
        'successTransfer' => 'Файл передан',
        'origin-x' => 'смещение по X',
        'origin-y' => 'смещение по Y',
        'original-image' => 'исходное изображение',
        'watermark-image' => 'водяной знак',
        'distance-x' => 'расстояние между водяными знаками по X',
        'distance-y' => 'расстояние между водяными знаками по Y',

    ),
    'en' => array(
        'title' => 'Watermarks generator',
        'settings' => 'Settings',
        'image' => 'Original image',
        'watermark' => 'Watermark',
        'position' => 'Position',
        'transparency' => 'Transparency',
        'reset' => 'Reset',
        'download' => 'Download',
        'copyright' => 'It`s my site, please, don`t copy or steal it.',
        'notInput' => 'Fill ',
        'notImage' => 'Choose ',
        'bigFile' => 'File size > 2MB',
        'wrongExtension' => 'Wrong extension',
        'wrongOrigin' => 'Wrong offset',
        'errorDownload' => 'Download error',
        'successTransfer' => 'File transferred',
        'origin-x' => 'offset X',
        'origin-y' => 'offset Y',
        'original-image' => 'original image',
        'watermark-image' => 'watermark',
        'distance-x' => 'X-distance between watermarks',
        'distance-y' => 'Y-distance between watermarks',
    )
);
